<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SeedMunicipioTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
     DB::table('municipios')->insert(
        array(
            array('cod_mpio' => '0101','municipio' => 'Guatemala','departamento_id' => 1),
            array('cod_mpio' => '0102','municipio' => 'Santa Catarina Pinula','departamento_id' => 1),
            array('cod_mpio' => '0103','municipio' => 'San José Pinula','departamento_id' => 1),
            array('cod_mpio' => '0104','municipio' => 'San José del Golfo','departamento_id' => 1),
            array('cod_mpio' => '0105','municipio' => 'Palencia','departamento_id' => 1),
            array('cod_mpio' => '0106','municipio' => 'Chinautla','departamento_id' => 1),
            array('cod_mpio' => '0107','municipio' => 'San Pedro Ayampuc','departamento_id' => 1),
            array('cod_mpio' => '0108','municipio' => 'Mixco','departamento_id' => 1),
            array('cod_mpio' => '0109','municipio' => 'San Pedro Sacatepéquez','departamento_id' => 1),
            array('cod_mpio' => '0110','municipio' => 'San Juan Sacatepéquez','departamento_id' => 1),
            array('cod_mpio' => '0111','municipio' => 'San Raymundo','departamento_id' => 1),
            array('cod_mpio' => '0112','municipio' => 'Chuarrancho','departamento_id' => 1),
            array('cod_mpio' => '0113','municipio' => 'Fraijanes','departamento_id' => 1),
            array('cod_mpio' => '0114','municipio' => 'Amatitlán','departamento_id' => 1),
            array('cod_mpio' => '0115','municipio' => 'Villa Nueva','departamento_id' => 1),
            array('cod_mpio' => '0116','municipio' => 'Villa Canales','departamento_id' => 1),
            array('cod_mpio' => '0117','municipio' => 'San Miguel Petapa','departamento_id' => 1),
            array('cod_mpio' => '0201','municipio' => 'Guastatoya','departamento_id' => 2),
            array('cod_mpio' => '0202','municipio' => 'Morazán','departamento_id' => 2),
            array('cod_mpio' => '0203','municipio' => 'San Agustín Acasaguastlán','departamento_id' => 2),
            array('cod_mpio' => '0204','municipio' => 'San Cristobal Acasaguastlán','departamento_id' => 2),
            array('cod_mpio' => '0205','municipio' => 'El Jícaro','departamento_id' => 2),
            array('cod_mpio' => '0206','municipio' => 'Sansare','departamento_id' => 2),
            array('cod_mpio' => '0207','municipio' => 'Sanarate','departamento_id' => 2),
            array('cod_mpio' => '0208','municipio' => 'San Antonio la Paz','departamento_id' => 2),
            array('cod_mpio' => '0301','municipio' => 'Antigua Guatemala','departamento_id' => 3),
            array('cod_mpio' => '0302','municipio' => 'Jocotenango','departamento_id' => 3),
            array('cod_mpio' => '0303','municipio' => 'Pastores','departamento_id' => 3),
            array('cod_mpio' => '0304','municipio' => 'Sumpango','departamento_id' => 3),
            array('cod_mpio' => '0305','municipio' => 'Santo Domingo Xenacoj','departamento_id' => 3),
            array('cod_mpio' => '0306','municipio' => 'Santiago Sacatepéquez','departamento_id' => 3),
            array('cod_mpio' => '0307','municipio' => 'San Bartolomé Milpas Altas','departamento_id' => 3),
            array('cod_mpio' => '0308','municipio' => 'San Lucas Sacatepéquez','departamento_id' => 3),
            array('cod_mpio' => '0309','municipio' => 'Santa Lucía Milpas Altas','departamento_id' => 3),
            array('cod_mpio' => '0310','municipio' => 'Magdalena Milpas Altas','departamento_id' => 3),
            array('cod_mpio' => '0311','municipio' => 'Santa María de Jesús','departamento_id' => 3),
            array('cod_mpio' => '0312','municipio' => 'Ciudad Vieja','departamento_id' => 3),
            array('cod_mpio' => '0313','municipio' => 'San Miguel Dueñas','departamento_id' => 3),
            array('cod_mpio' => '0314','municipio' => 'Alotenango','departamento_id' => 3),
            array('cod_mpio' => '0315','municipio' => 'San Antonio Aguas Calientes','departamento_id' => 3),
            array('cod_mpio' => '0316','municipio' => 'Santa Catarina Barahona','departamento_id' => 3),
            array('cod_mpio' => '0401','municipio' => 'Chimaltenango','departamento_id' => 4),
            array('cod_mpio' => '0402','municipio' => 'San José Poaquil','departamento_id' => 4),
            array('cod_mpio' => '0403','municipio' => 'San Martin Jilotepeque','departamento_id' => 4),
            array('cod_mpio' => '0404','municipio' => 'San Juan Comalapa','departamento_id' => 4),
            array('cod_mpio' => '0405','municipio' => 'Santa Apolonia','departamento_id' => 4),
            array('cod_mpio' => '0406','municipio' => 'Tecpan Guatemala','departamento_id' => 4),
            array('cod_mpio' => '0407','municipio' => 'Patzun','departamento_id' => 4),
            array('cod_mpio' => '0408','municipio' => 'San Miguel Pochuta','departamento_id' => 4),
            array('cod_mpio' => '0409','municipio' => 'Patzicia','departamento_id' => 4),
            array('cod_mpio' => '0410','municipio' => 'Santa Cruz Balanya','departamento_id' => 4),
            array('cod_mpio' => '0411','municipio' => 'Acatenango','departamento_id' => 4),
            array('cod_mpio' => '0412','municipio' => 'San Pedro Yepocapa','departamento_id' => 4),
            array('cod_mpio' => '0413','municipio' => 'San Andres Itzapa','departamento_id' => 4),
            array('cod_mpio' => '0414','municipio' => 'Parramos','departamento_id' => 4),
            array('cod_mpio' => '0415','municipio' => 'Zaragoza','departamento_id' => 4),
            array('cod_mpio' => '0416','municipio' => 'El Tejar','departamento_id' => 4),
            array('cod_mpio' => '0501','municipio' => 'Escuintla','departamento_id' => 5),
            array('cod_mpio' => '0502','municipio' => 'Santa Lucía Contzumalguapa','departamento_id' => 5),
            array('cod_mpio' => '0503','municipio' => 'La Democracia','departamento_id' => 5),
            array('cod_mpio' => '0504','municipio' => 'Siquinalá','departamento_id' => 5),
            array('cod_mpio' => '0505','municipio' => 'Masagua','departamento_id' => 5),
            array('cod_mpio' => '0506','municipio' => 'Tiquisate','departamento_id' => 5),
            array('cod_mpio' => '0507','municipio' => 'La Gomera','departamento_id' => 5),
            array('cod_mpio' => '0508','municipio' => 'Guanagazapa','departamento_id' => 5),
            array('cod_mpio' => '0509','municipio' => 'San José','departamento_id' => 5),
            array('cod_mpio' => '0510','municipio' => 'Iztapa','departamento_id' => 5),
            array('cod_mpio' => '0511','municipio' => 'Palín','departamento_id' => 5),
            array('cod_mpio' => '0512','municipio' => 'San Vicente Pacaya','departamento_id' => 5),
            array('cod_mpio' => '0513','municipio' => 'Nueva Concepción','departamento_id' => 5),
            array('cod_mpio' => '0514','municipio' => 'Sipacate','departamento_id' => 5),
            array('cod_mpio' => '0601','municipio' => 'Cuilapa','departamento_id' => 6),
            array('cod_mpio' => '0602','municipio' => 'Barberena','departamento_id' => 6),
            array('cod_mpio' => '0603','municipio' => 'Santa Rosa de Lima','departamento_id' => 6),
            array('cod_mpio' => '0604','municipio' => 'Casillas','departamento_id' => 6),
            array('cod_mpio' => '0605','municipio' => 'San Rafael las Flores','departamento_id' => 6),
            array('cod_mpio' => '0606','municipio' => 'Oratorio','departamento_id' => 6),
            array('cod_mpio' => '0607','municipio' => 'San Juan Tecuaco','departamento_id' => 6),
            array('cod_mpio' => '0608','municipio' => 'Chiquimulilla','departamento_id' => 6),
            array('cod_mpio' => '0609','municipio' => 'Taxisco','departamento_id' => 6),
            array('cod_mpio' => '0610','municipio' => 'Santa María Ixhuatán','departamento_id' => 6),
            array('cod_mpio' => '0611','municipio' => 'Guazacapan','departamento_id' => 6),
            array('cod_mpio' => '0612','municipio' => 'Santa Cruz Naranjo','departamento_id' => 6),
            array('cod_mpio' => '0613','municipio' => 'Pueblo Nuevo Viñas','departamento_id' => 6),
            array('cod_mpio' => '0614','municipio' => 'Nueva Santa Rosa','departamento_id' => 6),
            array('cod_mpio' => '0701','municipio' => 'Sololá','departamento_id' => 7),
            array('cod_mpio' => '0702','municipio' => 'San José Chacayá','departamento_id' => 7),
            array('cod_mpio' => '0703','municipio' => 'Santa María Visitación','departamento_id' => 7),
            array('cod_mpio' => '0704','municipio' => 'Santa Lucía Utatlán','departamento_id' => 7),
            array('cod_mpio' => '0705','municipio' => 'Nahualá','departamento_id' => 7),
            array('cod_mpio' => '0706','municipio' => 'Santa Catarina Ixtahuacán','departamento_id' => 7),
            array('cod_mpio' => '0707','municipio' => 'Santa Clara la Laguna','departamento_id' => 7),
            array('cod_mpio' => '0708','municipio' => 'Concepción','departamento_id' => 7),
            array('cod_mpio' => '0709','municipio' => 'San Andrés Semetabaj','departamento_id' => 7),
            array('cod_mpio' => '0710','municipio' => 'Panajachel','departamento_id' => 7),
            array('cod_mpio' => '0711','municipio' => 'Santa Catarina Palopó','departamento_id' => 7),
            array('cod_mpio' => '0712','municipio' => 'San Antonio Palopó','departamento_id' => 7),
            array('cod_mpio' => '0713','municipio' => 'San Lucas Tolimán','departamento_id' => 7),
            array('cod_mpio' => '0714','municipio' => 'Santa Cruz la Laguna','departamento_id' => 7),
            array('cod_mpio' => '0715','municipio' => 'San Pablo la Laguna','departamento_id' => 7),
            array('cod_mpio' => '0716','municipio' => 'San Marcos la Laguna','departamento_id' => 7),
            array('cod_mpio' => '0717','municipio' => 'San Juan la Laguna','departamento_id' => 7),
            array('cod_mpio' => '0718','municipio' => 'San Pedro la Laguna','departamento_id' => 7),
            array('cod_mpio' => '0719','municipio' => 'Santiago Atitlán','departamento_id' => 7),
            array('cod_mpio' => '0801','municipio' => 'Totonicapán','departamento_id' => 8),
            array('cod_mpio' => '0802','municipio' => 'San Cristobal Totonicapán','departamento_id' => 8),
            array('cod_mpio' => '0803','municipio' => 'San Francisco el Alto','departamento_id' => 8),
            array('cod_mpio' => '0804','municipio' => 'San Andrés Xecul','departamento_id' => 8),
            array('cod_mpio' => '0805','municipio' => 'Momostenango','departamento_id' => 8),
            array('cod_mpio' => '0806','municipio' => 'Santa María Chiquimula','departamento_id' => 8),
            array('cod_mpio' => '0807','municipio' => 'Santa Lucía la Reforma','departamento_id' => 8),
            array('cod_mpio' => '0808','municipio' => 'San Bartolo Aguas Calientes','departamento_id' => 8),
            array('cod_mpio' => '0901','municipio' => 'Quetzaltenango','departamento_id' => 9),
            array('cod_mpio' => '0902','municipio' => 'Salcajá','departamento_id' => 9),
            array('cod_mpio' => '0903','municipio' => 'Olintepeque','departamento_id' => 9),
            array('cod_mpio' => '0904','municipio' => 'San Carlos Sija','departamento_id' => 9),
            array('cod_mpio' => '0905','municipio' => 'Sibilia','departamento_id' => 9),
            array('cod_mpio' => '0906','municipio' => 'Cabrican','departamento_id' => 9),
            array('cod_mpio' => '0907','municipio' => 'Cajolá','departamento_id' => 9),
            array('cod_mpio' => '0908','municipio' => 'San Miguel Sigüilá','departamento_id' => 9),
            array('cod_mpio' => '0909','municipio' => 'San Juan Ostuncalco','departamento_id' => 9),
            array('cod_mpio' => '0910','municipio' => 'San Mateo','departamento_id' => 9),
            array('cod_mpio' => '0911','municipio' => 'Concepción Chiquirichapa','departamento_id' => 9),
            array('cod_mpio' => '0912','municipio' => 'San Martin Sacatepéquez','departamento_id' => 9),
            array('cod_mpio' => '0913','municipio' => 'Almolonga','departamento_id' => 9),
            array('cod_mpio' => '0914','municipio' => 'Cantel','departamento_id' => 9),
            array('cod_mpio' => '0915','municipio' => 'Huitán','departamento_id' => 9),
            array('cod_mpio' => '0916','municipio' => 'Zunil','departamento_id' => 9),
            array('cod_mpio' => '0917','municipio' => 'Colomba Costa Cuca','departamento_id' => 9),
            array('cod_mpio' => '0918','municipio' => 'San Francisco la Unión','departamento_id' => 9),
            array('cod_mpio' => '0919','municipio' => 'El Palmar','departamento_id' => 9),
            array('cod_mpio' => '0920','municipio' => 'Coatepeque','departamento_id' => 9),
            array('cod_mpio' => '0921','municipio' => 'Génova Costa Cuca','departamento_id' => 9),
            array('cod_mpio' => '0922','municipio' => 'Flores Costa Cuca','departamento_id' => 9),
            array('cod_mpio' => '0923','municipio' => 'La Esperanza','departamento_id' => 9),
            array('cod_mpio' => '0924','municipio' => 'Palestina de los Altos','departamento_id' => 9),
            array('cod_mpio' => '1001','municipio' => 'Mazatenango','departamento_id' => 10),
            array('cod_mpio' => '1002','municipio' => 'Cuyotenango','departamento_id' => 10),
            array('cod_mpio' => '1003','municipio' => 'San Francisco Zapotitlán','departamento_id' => 10),
            array('cod_mpio' => '1004','municipio' => 'San Bernardino','departamento_id' => 10),
            array('cod_mpio' => '1005','municipio' => 'San José el Ídolo','departamento_id' => 10),
            array('cod_mpio' => '1006','municipio' => 'Santo Domingo Suchitepéquez','departamento_id' => 10),
            array('cod_mpio' => '1007','municipio' => 'San Lorenzo','departamento_id' => 10),
            array('cod_mpio' => '1008','municipio' => 'Samayac','departamento_id' => 10),
            array('cod_mpio' => '1009','municipio' => 'San Pablo Jocopilas','departamento_id' => 10),
            array('cod_mpio' => '1010','municipio' => 'San Antonio Suchitepéquez','departamento_id' => 10),
            array('cod_mpio' => '1011','municipio' => 'San Miguel Panam','departamento_id' => 10),
            array('cod_mpio' => '1012','municipio' => 'San Gabriel','departamento_id' => 10),
            array('cod_mpio' => '1013','municipio' => 'Chicacao','departamento_id' => 10),
            array('cod_mpio' => '1014','municipio' => 'Patulul','departamento_id' => 10),
            array('cod_mpio' => '1015','municipio' => 'Santa Bárbara','departamento_id' => 10),
            array('cod_mpio' => '1016','municipio' => 'San Juan Bautista','departamento_id' => 10),
            array('cod_mpio' => '1017','municipio' => 'Santo Tomás la Unión','departamento_id' => 10),
            array('cod_mpio' => '1018','municipio' => 'Zunilito','departamento_id' => 10),
            array('cod_mpio' => '1019','municipio' => 'Pueblo Nuevo','departamento_id' => 10),
            array('cod_mpio' => '1020','municipio' => 'Rio Bravo','departamento_id' => 10),
            array('cod_mpio' => '1021','municipio' => 'San José la Máquina','departamento_id' => 10),
            array('cod_mpio' => '1101','municipio' => 'Retalhuleu','departamento_id' => 11),
            array('cod_mpio' => '1102','municipio' => 'San Sebastian','departamento_id' => 11),
            array('cod_mpio' => '1103','municipio' => 'Santa Cruz Muluá','departamento_id' => 11),            
            array('cod_mpio' => '1104','municipio' => 'San Martín Zapotitlán','departamento_id' => 11),
            array('cod_mpio' => '1105','municipio' => 'San Felipe','departamento_id' => 11),
            array('cod_mpio' => '1106','municipio' => 'San Andres Villa Seca','departamento_id' => 11),
            array('cod_mpio' => '1107','municipio' => 'Champerico','departamento_id' => 11),
            array('cod_mpio' => '1108','municipio' => 'Nuevo San Carlos','departamento_id' => 11),
            array('cod_mpio' => '1109','municipio' => 'El Asintal','departamento_id' => 11),
            array('cod_mpio' => '1201','municipio' => 'San Marcos','departamento_id' => 12),
            array('cod_mpio' => '1202','municipio' => 'San Pedro Sacatepéquez','departamento_id' => 12),
            array('cod_mpio' => '1203','municipio' => 'San Antonio Sacatepéquez','departamento_id' => 12),
            array('cod_mpio' => '1204','municipio' => 'Comitancillo','departamento_id' => 12),
            array('cod_mpio' => '1205','municipio' => 'San Miguel Ixtahuacán','departamento_id' => 12),
            array('cod_mpio' => '1206','municipio' => 'Concepción Tutuapa','departamento_id' => 12),
            array('cod_mpio' => '1207','municipio' => 'Tacaná','departamento_id' => 12),
            array('cod_mpio' => '1208','municipio' => 'Sibinal','departamento_id' => 12),
            array('cod_mpio' => '1209','municipio' => 'Tajumulco','departamento_id' => 12),
            array('cod_mpio' => '1210','municipio' => 'Tejutla','departamento_id' => 12),
            array('cod_mpio' => '1211','municipio' => 'San Rafael Pie de la Cuesta','departamento_id' => 12),
            array('cod_mpio' => '1212','municipio' => 'Nuevo Progreso','departamento_id' => 12),
            array('cod_mpio' => '1213','municipio' => 'El Tumbador','departamento_id' => 12),
            array('cod_mpio' => '1214','municipio' => 'San José el Rodeo','departamento_id' => 12),
            array('cod_mpio' => '1215','municipio' => 'Malacatán','departamento_id' => 12),
            array('cod_mpio' => '1216','municipio' => 'Catarina','departamento_id' => 12),
            array('cod_mpio' => '1217','municipio' => 'Ayutla (Tecún Uman)','departamento_id' => 12),
            array('cod_mpio' => '1218','municipio' => 'Ocós','departamento_id' => 12),
            array('cod_mpio' => '1219','municipio' => 'San Pablo','departamento_id' => 12),
            array('cod_mpio' => '1220','municipio' => 'El Quetzal','departamento_id' => 12),
            array('cod_mpio' => '1221','municipio' => 'La Reforma','departamento_id' => 12),
            array('cod_mpio' => '1222','municipio' => 'Pajapita','departamento_id' => 12),
            array('cod_mpio' => '1223','municipio' => 'Ixchiguan','departamento_id' => 12),
            array('cod_mpio' => '1224','municipio' => 'San José Ojetenam','departamento_id' => 12),
            array('cod_mpio' => '1225','municipio' => 'San Cristobal Cucho','departamento_id' => 12),
            array('cod_mpio' => '1226','municipio' => 'Sipacapa','departamento_id' => 12),
            array('cod_mpio' => '1227','municipio' => 'Esquipulas Palo Gordo','departamento_id' => 12),
            array('cod_mpio' => '1228','municipio' => 'Rio Blanco','departamento_id' => 12),
            array('cod_mpio' => '1229','municipio' => 'San Lorenzo','departamento_id' => 12),
            array('cod_mpio' => '1230','municipio' => 'La Blanca','departamento_id' => 12),
            array('cod_mpio' => '1301','municipio' => 'Huehuetenango','departamento_id' => 13),
            array('cod_mpio' => '1302','municipio' => 'Chiantla','departamento_id' => 13),
            array('cod_mpio' => '1303','municipio' => 'Malacatancito','departamento_id' => 13),
            array('cod_mpio' => '1304','municipio' => 'Cuilco','departamento_id' => 13),
            array('cod_mpio' => '1305','municipio' => 'Nentón','departamento_id' => 13),
            array('cod_mpio' => '1306','municipio' => 'San Pedro Necta','departamento_id' => 13),
            array('cod_mpio' => '1307','municipio' => 'Jacaltenango','departamento_id' => 13),
            array('cod_mpio' => '1308','municipio' => 'San Pedro Soloma','departamento_id' => 13),
            array('cod_mpio' => '1309','municipio' => 'San Idelfonso Ixtahuacan','departamento_id' => 13),
            array('cod_mpio' => '1310','municipio' => 'Santa Bárbara','departamento_id' => 13),
            array('cod_mpio' => '1311','municipio' => 'La Libertad','departamento_id' => 13),
            array('cod_mpio' => '1312','municipio' => 'La Democracia','departamento_id' => 13),
            array('cod_mpio' => '1313','municipio' => 'San Miguel Acatán','departamento_id' => 13),
            array('cod_mpio' => '1314','municipio' => 'San Rafael la Independencia','departamento_id' => 13),
            array('cod_mpio' => '1315','municipio' => 'Todos Santos Cuchumatanes','departamento_id' => 13),
            array('cod_mpio' => '1316','municipio' => 'San Juan Atitán','departamento_id' => 13),
            array('cod_mpio' => '1317','municipio' => 'Santa Eulalia','departamento_id' => 13),
            array('cod_mpio' => '1318','municipio' => 'San Mateo Ixtatán','departamento_id' => 13),
            array('cod_mpio' => '1319','municipio' => 'Colotenango','departamento_id' => 13),
            array('cod_mpio' => '1320','municipio' => 'San Sebastian Huehuetenango','departamento_id' => 13),
            array('cod_mpio' => '1321','municipio' => 'Tectitán','departamento_id' => 13),
            array('cod_mpio' => '1322','municipio' => 'Concepción Huista','departamento_id' => 13),
            array('cod_mpio' => '1323','municipio' => 'San Juan Ixcoy','departamento_id' => 13),
            array('cod_mpio' => '1324','municipio' => 'San Antonio Huista','departamento_id' => 13),
            array('cod_mpio' => '1325','municipio' => 'San Sebastian Coatán','departamento_id' => 13),
            array('cod_mpio' => '1326','municipio' => 'Santa Cruz Barillas','departamento_id' => 13),
            array('cod_mpio' => '1327','municipio' => 'Aguacatán','departamento_id' => 13),
            array('cod_mpio' => '1328','municipio' => 'San Rafael Petzal','departamento_id' => 13),
            array('cod_mpio' => '1329','municipio' => 'San Gaspar Ixchil','departamento_id' => 13),
            array('cod_mpio' => '1330','municipio' => 'Santiago Chimaltenango','departamento_id' => 13),
            array('cod_mpio' => '1331','municipio' => 'Santa Ana Huista','departamento_id' => 13),
            array('cod_mpio' => '1332','municipio' => 'Unión Cantinil','departamento_id' => 13),
            array('cod_mpio' => '1333','municipio' => 'Petatán','departamento_id' => 13),
            array('cod_mpio' => '1401','municipio' => 'Santa Cruz del Quiché','departamento_id' => 14),
            array('cod_mpio' => '1402','municipio' => 'Chiché','departamento_id' => 14),
            array('cod_mpio' => '1403','municipio' => 'Chiniqué','departamento_id' => 14),
            array('cod_mpio' => '1404','municipio' => 'Zacualpa','departamento_id' => 14),
            array('cod_mpio' => '1405','municipio' => 'Chajul','departamento_id' => 14),
            array('cod_mpio' => '1406','municipio' => 'Santo Tomás Chichicastenango','departamento_id' => 14),
            array('cod_mpio' => '1407','municipio' => 'Patzité','departamento_id' => 14),
            array('cod_mpio' => '1408','municipio' => 'San Antonio Ilotenango','departamento_id' => 14),
            array('cod_mpio' => '1409','municipio' => 'San Pedro Jocopilas','departamento_id' => 14),
            array('cod_mpio' => '1410','municipio' => 'Cunén','departamento_id' => 14),
            array('cod_mpio' => '1411','municipio' => 'San Juan Cotzal','departamento_id' => 14),
            array('cod_mpio' => '1412','municipio' => 'Joyabaj','departamento_id' => 14),
            array('cod_mpio' => '1413','municipio' => 'Nebaj','departamento_id' => 14),
            array('cod_mpio' => '1414','municipio' => 'San Andrés Sajcabajá','departamento_id' => 14),
            array('cod_mpio' => '1415','municipio' => 'San Miguel Uspantán','departamento_id' => 14),
            array('cod_mpio' => '1416','municipio' => 'Sacapulas','departamento_id' => 14),
            array('cod_mpio' => '1417','municipio' => 'San Bartolomé Jocotenango','departamento_id' => 14),
            array('cod_mpio' => '1418','municipio' => 'Canillá','departamento_id' => 14),
            array('cod_mpio' => '1419','municipio' => 'Chicamán','departamento_id' => 14),
            array('cod_mpio' => '1420','municipio' => 'Ixcán','departamento_id' => 14),
            array('cod_mpio' => '1421','municipio' => 'Pachalun','departamento_id' => 14),
            array('cod_mpio' => '1501','municipio' => 'Salamá','departamento_id' => 15),
            array('cod_mpio' => '1502','municipio' => 'San Miguel Chicaj','departamento_id' => 15),
            array('cod_mpio' => '1503','municipio' => 'Rabinal','departamento_id' => 15),
            array('cod_mpio' => '1504','municipio' => 'Cubulco','departamento_id' => 15),
            array('cod_mpio' => '1505','municipio' => 'Granados','departamento_id' => 15),
            array('cod_mpio' => '1506','municipio' => 'Santa Cruz el Chol','departamento_id' => 15),
            array('cod_mpio' => '1507','municipio' => 'San Jerónimo','departamento_id' => 15),
            array('cod_mpio' => '1508','municipio' => 'Purulhá','departamento_id' => 15),
            array('cod_mpio' => '1601','municipio' => 'Cobán','departamento_id' => 16),
            array('cod_mpio' => '1602','municipio' => 'Santa Cruz Verapaz','departamento_id' => 16),
            array('cod_mpio' => '1603','municipio' => 'San Cristobal Verapaz','departamento_id' => 16),
            array('cod_mpio' => '1604','municipio' => 'Tactic','departamento_id' => 16),
            array('cod_mpio' => '1605','municipio' => 'Tamahú','departamento_id' => 16),
            array('cod_mpio' => '1606','municipio' => 'San Miguel Tucurú','departamento_id' => 16),
            array('cod_mpio' => '1607','municipio' => 'Panzos','departamento_id' => 16),
            array('cod_mpio' => '1608','municipio' => 'Senahú','departamento_id' => 16),
            array('cod_mpio' => '1609','municipio' => 'San Pedro Carchá','departamento_id' => 16),
            array('cod_mpio' => '1610','municipio' => 'San Juan Chamelco','departamento_id' => 16),
            array('cod_mpio' => '1611','municipio' => 'Lanquín','departamento_id' => 16),
            array('cod_mpio' => '1612','municipio' => 'Santa María Cahabón','departamento_id' => 16),
            array('cod_mpio' => '1613','municipio' => 'Chisec','departamento_id' => 16),
            array('cod_mpio' => '1614','municipio' => 'Chahal','departamento_id' => 16),
            array('cod_mpio' => '1615','municipio' => 'Fray Bartolomé de las Casas','departamento_id' => 16),
            array('cod_mpio' => '1616','municipio' => 'Santa Catalina la Tinta','departamento_id' => 16),
            array('cod_mpio' => '1617','municipio' => 'Raxruhá','departamento_id' => 16),
            array('cod_mpio' => '1701','municipio' => 'Flores','departamento_id' => 17),
            array('cod_mpio' => '1702','municipio' => 'San José','departamento_id' => 17),
            array('cod_mpio' => '1703','municipio' => 'San Benito','departamento_id' => 17),
            array('cod_mpio' => '1704','municipio' => 'San Andrés','departamento_id' => 17),
            array('cod_mpio' => '1705','municipio' => 'La Libertad','departamento_id' => 17),
            array('cod_mpio' => '1706','municipio' => 'San Francisco','departamento_id' => 17),
            array('cod_mpio' => '1707','municipio' => 'Santa Ana','departamento_id' => 17),
            array('cod_mpio' => '1708','municipio' => 'Dolores','departamento_id' => 17),
            array('cod_mpio' => '1709','municipio' => 'San Luis','departamento_id' => 17),
            array('cod_mpio' => '1710','municipio' => 'Sayaxché','departamento_id' => 17),
            array('cod_mpio' => '1711','municipio' => 'Melchor de Mencos','departamento_id' => 17),
            array('cod_mpio' => '1712','municipio' => 'Peptún','departamento_id' => 17),
            array('cod_mpio' => '1713','municipio' => 'Las Cruces','departamento_id' => 17),
            array('cod_mpio' => '1714','municipio' => 'El Chal','departamento_id' => 17),
            array('cod_mpio' => '1801','municipio' => 'Puerto Barrios','departamento_id' => 18),
            array('cod_mpio' => '1802','municipio' => 'Livingston','departamento_id' => 18),
            array('cod_mpio' => '1803','municipio' => 'El Estor','departamento_id' => 18),
            array('cod_mpio' => '1804','municipio' => 'Morales','departamento_id' => 18),
            array('cod_mpio' => '1805','municipio' => 'Los Amates','departamento_id' => 18),
            array('cod_mpio' => '1901','municipio' => 'Zacapa','departamento_id' => 19),
            array('cod_mpio' => '1902','municipio' => 'Estanzuela','departamento_id' => 19),
            array('cod_mpio' => '1903','municipio' => 'Rio Hondo','departamento_id' => 19),
            array('cod_mpio' => '1904','municipio' => 'Gualán','departamento_id' => 19),
            array('cod_mpio' => '1905','municipio' => 'Teculután','departamento_id' => 19),
            array('cod_mpio' => '1906','municipio' => 'Usumatlán','departamento_id' => 19),
            array('cod_mpio' => '1907','municipio' => 'Cabañas','departamento_id' => 19),
            array('cod_mpio' => '1908','municipio' => 'San Diego','departamento_id' => 19),
            array('cod_mpio' => '1909','municipio' => 'La Unión','departamento_id' => 19),
            array('cod_mpio' => '1910','municipio' => 'Huité','departamento_id' => 19),
            array('cod_mpio' => '1911','municipio' => 'San Jorge','departamento_id' => 19),
            array('cod_mpio' => '2001','municipio' => 'Chiquimula','departamento_id' => 20),
            array('cod_mpio' => '2002','municipio' => 'San José la Arada','departamento_id' => 20),
            array('cod_mpio' => '2003','municipio' => 'San Juan Ermita','departamento_id' => 20),
            array('cod_mpio' => '2004','municipio' => 'Jocotán','departamento_id' => 20),
            array('cod_mpio' => '2005','municipio' => 'Camotan','departamento_id' => 20),
            array('cod_mpio' => '2006','municipio' => 'Olopa','departamento_id' => 20),
            array('cod_mpio' => '2007','municipio' => 'Esquipulas','departamento_id' => 20),
            array('cod_mpio' => '2008','municipio' => 'Concepción las Minas','departamento_id' => 20),
            array('cod_mpio' => '2009','municipio' => 'Quezaltepeque','departamento_id' => 20),
            array('cod_mpio' => '2010','municipio' => 'San Jacinto','departamento_id' => 20),
            array('cod_mpio' => '2011','municipio' => 'Ipala','departamento_id' => 20),
            array('cod_mpio' => '2101','municipio' => 'Jalapa','departamento_id' => 21),
            array('cod_mpio' => '2102','municipio' => 'San Pedro Pinula','departamento_id' => 21),
            array('cod_mpio' => '2103','municipio' => 'San Luis Jilotepeque','departamento_id' => 21),
            array('cod_mpio' => '2104','municipio' => 'San Manuel Chaparrón','departamento_id' => 21),
            array('cod_mpio' => '2105','municipio' => 'San Carlos Alzatate','departamento_id' => 21),
            array('cod_mpio' => '2106','municipio' => 'Monjas','departamento_id' => 21),
            array('cod_mpio' => '2107','municipio' => 'Mataquescuintla','departamento_id' => 21),
            array('cod_mpio' => '2201','municipio' => 'Jutiapa','departamento_id' => 22),
            array('cod_mpio' => '2202','municipio' => 'El Progreso','departamento_id' => 22),
            array('cod_mpio' => '2203','municipio' => 'Santa Catarina Mita','departamento_id' => 22),
            array('cod_mpio' => '2204','municipio' => 'Agua Blanca','departamento_id' => 22),
            array('cod_mpio' => '2205','municipio' => 'Asunción Mita','departamento_id' => 22),
            array('cod_mpio' => '2206','municipio' => 'Yupiltepeque','departamento_id' => 22),
            array('cod_mpio' => '2207','municipio' => 'Atescatempa','departamento_id' => 22),
            array('cod_mpio' => '2208','municipio' => 'Jerez','departamento_id' => 22),
            array('cod_mpio' => '2209','municipio' => 'El Adelanto','departamento_id' => 22),
            array('cod_mpio' => '2210','municipio' => 'Zapotitlán','departamento_id' => 22),
            array('cod_mpio' => '2211','municipio' => 'Comapa','departamento_id' => 22),
            array('cod_mpio' => '2212','municipio' => 'Jalpatagua','departamento_id' => 22),
            array('cod_mpio' => '2213','municipio' => 'Conguaco','departamento_id' => 22),
            array('cod_mpio' => '2214','municipio' => 'Moyuta','departamento_id' => 22),
            array('cod_mpio' => '2215','municipio' => 'Pasaco','departamento_id' => 22),
            array('cod_mpio' => '2216','municipio' => 'San José Acatempa','departamento_id' => 22),
            array('cod_mpio' => '2217','municipio' => 'Quesada','departamento_id' => 22),
            )
        );
 }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('municipios')->delete();
    }
}
